# this repo is replicated in the .git/hooks using the same name; this is for clarity
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.5
      hooks:
        - id: no-commit-to-branch
          args: ['--branch', 'master']