version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./webapp-flask/templates:/usr/share/nginx/html 
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend

  # the flask backend  
  backend:
    image: pwein/flask-webapp:latest-backend
    expose: ["5000"]
    networks:
      - app-network

  # the flask frontend
  frontend:
    image: pwein/flask-webapp:latest-frontend
    expose: ["3000"]
    networks:
      - app-network
      
#Docker Networks
networks:
  app-network:
    driver: bridge